theme = "solarized-dark"
icons = "awesome"


[[block]]
block = "music"
max_width = 21
marquee = true
player = "spotify"
buttons = ["play", "next"]




[[block]]
block = "backlight"


#[[block]]
#block = "speedtest"
#bytes = true
#interval = 1


[[block]]
block = "net"
device = "wlo1"
ssid = false
ip = true
speed_up = true
graph_up = true
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

#[[block]]
#block = "memory"
#display_type = "memory"
#format_mem = "{Mup}%"
#format_swap = "{SUp}%"



[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %I:%M %p"

[[block]]
block = "battery"
interval = 4




#theme = "solarized-dark"
#icons = "awesome"

[[block]]
block = "temperature"


#[[block]]
#block = "load"
#interval = 1
#format = "{1m} {5m} {15m}"

#[[block]]
#block = "cpu"
#interval = 0.7

#[[block]]
#block = "memory"
#interval = 5
#info_type = "memory"
#format_mem = "{Mup}%"
#format_swap = "{SUp}%"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20

#[[block]]
#block = "disk_space"
#path = "/home/user"
#alias = "~"
#info_type = "available"
#unit = "GB"
#interval = 20

#[[block]]
#block = "battery"
#device = 0

#[[block]]
#block = "sound"

#[[block]]
##block = "time"
#interval = 60
#format = "%a %d/%m %R"

[[block]]
block = "custom"
interval = 999999
command = "echo '\uF011'"
on_click = "i3-nagbar -t warning -m 'What do you want to do?' -b 'Shutdown' 'shutdown now' -b 'Hibernate' 'systemctl hibernate' -b 'Reboot' 'reboot'"


